runtime: python310

entrypoint: gunicorn -b :$PORT app_config.wsgi:application

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "app_config.settings"

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*  # すべてのリクエストを Django アプリケーションにルーティング
    script: auto
